// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDepo.Data;

#nullable disable

namespace WebDepo.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebDepo.Barkod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AnaEtiket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("DepoKodu")
                        .HasColumnType("smallint");

                    b.Property<bool>("DepodaMi")
                        .HasColumnType("bit");

                    b.Property<string>("Etiket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("Gkk")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("KoliEtiketi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MalKabulEtiketi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Miktar")
                        .HasColumnType("double(30, 8)");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaletEtiketi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PartiNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RafEtiketi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Skt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StokKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("silindiMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TBLEtiket");
                });

            modelBuilder.Entity("WebDepo.DepoTransferMas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BelgeSeri")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CariKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("CikisDepo")
                        .HasColumnType("smallint");

                    b.Property<bool>("EIrsaliyeMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEmriTamamlandiMi")
                        .HasColumnType("bit");

                    b.Property<bool>("NetsiseAtildiMi")
                        .HasColumnType("bit");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SiparisNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UretimIsEmriNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("VarisDepo")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("TBLDepoTransferMas");
                });

            modelBuilder.Entity("WebDepo.DepoTransferTalep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DepoTransferMasId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<double>("Miktar")
                        .HasColumnType("double(30, 8)");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OnayDurumu")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OnaylamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeriNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StokKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TBLDepoTransferTalep");
                });

            modelBuilder.Entity("WebDepo.DepoTransferTra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DepoTransferMasId")
                        .HasColumnType("bigint");

                    b.Property<long>("EtiketId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TBLDepoTransferTra");
                });

            modelBuilder.Entity("WebDepo.EIrsaliyeDepoTanimi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CariKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("CikisDepo")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("VarisDepo")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("TBLEIrsaliyeDepoTanimi");
                });

            modelBuilder.Entity("WebDepo.EtiketGecmisiMas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short>("AnaDepoKodu")
                        .HasColumnType("smallint");

                    b.Property<long>("AnaEtiketId")
                        .HasColumnType("bigint");

                    b.Property<double>("AnaEtiketMiktari")
                        .HasColumnType("double(18,2)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("IslemTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("OlusanDepoKodu")
                        .HasColumnType("smallint");

                    b.Property<long>("OlusanEtiketId")
                        .HasColumnType("bigint");

                    b.Property<double>("OlusanEtiketMiktari")
                        .HasColumnType("double(18,2)");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TBLEtiketGecmisi");
                });

            modelBuilder.Entity("WebDepo.IrsaliyeSiparisEsleme", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("IrsaliyeNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IrsaliyeTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("MalKabulId")
                        .HasColumnType("bigint");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SiparisNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("silindiMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TBLIrsaliyeSiparisEsleme");
                });

            modelBuilder.Entity("WebDepo.KullaniciSirketEsleme", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long>("KullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TBLKullaniciSirketEsleme");
                });

            modelBuilder.Entity("WebDepo.MalKabul", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DepoKodu")
                        .HasColumnType("int");

                    b.Property<string>("Etiket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("IrsaliyeNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("NetsiseAtildiMi")
                        .HasColumnType("bit");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartiNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Skt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("silindiMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TBLMalKabul");
                });

            modelBuilder.Entity("WebDepo.OnayliDatDepoTanimlama", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short>("CikisDepo")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("VarisDepo")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("TBLOnayliDatDepoTanimlama");
                });

            modelBuilder.Entity("WebDepo.Raf", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("DepoKodu")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<double>("MaxRafAgirligi")
                        .HasColumnType("double(18,2)");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("RafEtiket")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RafHacmi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RafKodu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ust")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TBLRaf");
                });

            modelBuilder.Entity("WebDepo.Recete", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<double>("Miktar")
                        .HasColumnType("double(30, 8)");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StokKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("UskId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TBLRecete");
                });

            modelBuilder.Entity("WebDepo.SevkMas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BelgeSeri")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CariKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("CikisDepo")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEmriTamamlandiMi")
                        .HasColumnType("bit");

                    b.Property<bool>("NetsiseAtildiMi")
                        .HasColumnType("bit");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TBLSevkMas");
                });

            modelBuilder.Entity("WebDepo.SevkTalep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<int>("KalemSiraNo")
                        .HasColumnType("int");

                    b.Property<double>("Miktar")
                        .HasColumnType("double(30, 8)");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeriNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("SevkId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SiparisNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StokKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TBLSevkTalep");
                });

            modelBuilder.Entity("WebDepo.SevkTra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EtiketId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SevkId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TBLSevkTra");
                });

            modelBuilder.Entity("WebDepo.Sirketler", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SirketDBAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SirketDBIp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SirketDBKullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SirketDBSifre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TBLSirketler");
                });

            modelBuilder.Entity("WebDepo.Terminal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TerminalNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TBLTerminal");
                });

            modelBuilder.Entity("WebDepo.TerminalUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("TerminalId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TBLTerminalUser");
                });

            modelBuilder.Entity("WebDepo.USK", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BelgeSeri")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<long>("EtiketId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long>("IsEmriId")
                        .HasColumnType("bigint");

                    b.Property<string>("IsEmriNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("NetsiseAtildiMi")
                        .HasColumnType("bit");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("UretimDepo")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("TBLUsk");
                });

            modelBuilder.Entity("WebDepo.UretimMas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BelgeSeri")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<short>("CikisDepo")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEmriTamamlandiMi")
                        .HasColumnType("bit");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UretimIsEmriNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("VarisDepo")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("TBLUretimMas");
                });

            modelBuilder.Entity("WebDepo.UretimTalep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<double>("Miktar")
                        .HasColumnType("double(30, 8)");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OnayDurumu")
                        .HasColumnType("bit");

                    b.Property<string>("SeriNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StokKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("UretimMasId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TBLUretimTalep");
                });

            modelBuilder.Entity("WebDepo.UretimTra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EtiketId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("UretimMasId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TBLUretimTra");
                });

            modelBuilder.Entity("WebDepo.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TBLUser");
                });

            modelBuilder.Entity("WebDepo.UskTuketim", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EtiketId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<double>("Miktar")
                        .HasColumnType("double(30, 8)");

                    b.Property<long>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SirketKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("UskId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TBLUskTuketim");
                });
#pragma warning restore 612, 618
        }
    }
}
